framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            doctrine.second_level_cache_pool:
                adapter: cache.adapter.redis
