when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
        excluded_ajax_paths: '^/((index|app(_[\w]+)?).php/)?_wdt'

    framework:
        profiler:
            enabled: true
            collect: true
            collect_parameter: null
            only_exceptions: false
            dsn: 'file:%kernel.cache_dir%/profiler'

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
